version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Swiftwallet
      POSTGRES_PASSWORD: AayushAashish
      POSTGRES_DB: Swiftwallet
    ports:
      - "786:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
